/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWriteRouteImport } from './routes/_authenticated/write'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedDraftsRouteImport } from './routes/_authenticated/drafts'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedPoemsIdRouteImport } from './routes/_authenticated/poems.$id'
import { Route as AuthenticatedPoemsIdEditRouteImport } from './routes/_authenticated/poems.$id_.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWriteRoute = AuthenticatedWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDraftsRoute = AuthenticatedDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoemsIdRoute = AuthenticatedPoemsIdRouteImport.update({
  id: '/poems/$id',
  path: '/poems/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoemsIdEditRoute =
  AuthenticatedPoemsIdEditRouteImport.update({
    id: '/poems/$id_/edit',
    path: '/poems/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/write': typeof AuthenticatedWriteRoute
  '/poems/$id': typeof AuthenticatedPoemsIdRoute
  '/poems/$id/edit': typeof AuthenticatedPoemsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/write': typeof AuthenticatedWriteRoute
  '/poems/$id': typeof AuthenticatedPoemsIdRoute
  '/poems/$id/edit': typeof AuthenticatedPoemsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/drafts': typeof AuthenticatedDraftsRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/_authenticated/write': typeof AuthenticatedWriteRoute
  '/_authenticated/poems/$id': typeof AuthenticatedPoemsIdRoute
  '/_authenticated/poems/$id_/edit': typeof AuthenticatedPoemsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/archive'
    | '/calendar'
    | '/drafts'
    | '/favorites'
    | '/journal'
    | '/settings'
    | '/trash'
    | '/write'
    | '/poems/$id'
    | '/poems/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/archive'
    | '/calendar'
    | '/drafts'
    | '/favorites'
    | '/journal'
    | '/settings'
    | '/trash'
    | '/write'
    | '/poems/$id'
    | '/poems/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/archive'
    | '/_authenticated/calendar'
    | '/_authenticated/drafts'
    | '/_authenticated/favorites'
    | '/_authenticated/journal'
    | '/_authenticated/settings'
    | '/_authenticated/trash'
    | '/_authenticated/write'
    | '/_authenticated/poems/$id'
    | '/_authenticated/poems/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/write': {
      id: '/_authenticated/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof AuthenticatedWriteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drafts': {
      id: '/_authenticated/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AuthenticatedDraftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/poems/$id': {
      id: '/_authenticated/poems/$id'
      path: '/poems/$id'
      fullPath: '/poems/$id'
      preLoaderRoute: typeof AuthenticatedPoemsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/poems/$id_/edit': {
      id: '/_authenticated/poems/$id_/edit'
      path: '/poems/$id/edit'
      fullPath: '/poems/$id/edit'
      preLoaderRoute: typeof AuthenticatedPoemsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDraftsRoute: typeof AuthenticatedDraftsRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedWriteRoute: typeof AuthenticatedWriteRoute
  AuthenticatedPoemsIdRoute: typeof AuthenticatedPoemsIdRoute
  AuthenticatedPoemsIdEditRoute: typeof AuthenticatedPoemsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDraftsRoute: AuthenticatedDraftsRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedWriteRoute: AuthenticatedWriteRoute,
  AuthenticatedPoemsIdRoute: AuthenticatedPoemsIdRoute,
  AuthenticatedPoemsIdEditRoute: AuthenticatedPoemsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
